import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-[615px]">
        <div className="aspect-w-3 aspect-h-1 bg-neutral-50"></div>
        <div className="m-2 mx-6">
          <div className="flex">
            <div className="relative shrink-0 basis-[100px]">
              <div className="absolute top-[-50px] h-[100px] w-[100px] rounded-full border-2 border-white bg-neutral-500"></div>
            </div>
            <div className="ml-3.5 min-w-0">
              <p className="text-lg">Elio Programs</p>
              <p className="overflow-hidden text-ellipsis">elio@gmail.com</p>
            </div>
          </div>
          <div className="mt-7">Summary</div>
          <div className="mt-3.5 flex">
            <p>
              <span className="font-semibold">211</span>
              &nbsp;Followers
            </p>
            <p>
              <span className="ml-5 font-semibold">300</span>&nbsp;Following
            </p>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
